# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x02\x66l\"\x1f\n\x0cModelWeights\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t20\n\x06\x46LPeer\x12&\n\tSendModel\x12\x10.fl.ModelWeights\x1a\x07.fl.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELWEIGHTS']._serialized_start=19
  _globals['_MODELWEIGHTS']._serialized_end=50
  _globals['_ACK']._serialized_start=52
  _globals['_ACK']._serialized_end=74
  _globals['_FLPEER']._serialized_start=76
  _globals['_FLPEER']._serialized_end=124
# @@protoc_insertion_point(module_scope)
